### ISSUE TITLE
Game crashes when hit by a creaking mob.

### ISSUE THREAD

**Issue by T0RNATO** [RedVortexDev/CreakingDepths#1]
https://mclo.gs/5fchZnC

**Comment by RedVortexDev** [comment]
will look into

**Comment by RedVortexDev** [comment]
hey, sorry for taking long.. could you try getting the mod from the latest commit?
https://github.com/RedVortexDev/CreakingDepths/actions/runs/11274812036
![image](https://github.com/user-attachments/assets/1aca8a74-70bf-4e3b-b586-89836d6d9c79)

**Comment by RedVortexDev** [comment]
try: https://modrinth.com/mod/creaking-depths/version/1.1
